name: Build Docker Images

on:
  push:
    branches:    
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Docker login
      run: docker login --username fropenbanking --password "${{ secrets.DOCKER_HUB_PASSWORD }}"
    - name: Build with Maven
      run: mvn -B install --file pom.xml
    - name: Push docker images
      run: mvn -B dockerfile:push
    - name: Push docker images latest
      run: mvn -B dockerfile:push@push-image-latest-tag